### ISSUE TITLE
IP2Location - An error occurred

### ISSUE THREAD

**Issue by CinematicTree9** [ip2location/ip2location-piwik#108]
Hello, after upgrade Matamo server to the latest 5.0.3 version IP2Location plugin didn't work "An unexpected website was found in the request: website id was set to '1'.

![image](https://github.com/ip2location/ip2location-piwik/assets/52570208/a401c926-8d53-4c12-b191-551020a93f0f)
![image](https://github.com/ip2location/ip2location-piwik/assets/52570208/ddfe466a-36d2-4140-aa4f-bb0e713f0907)

I try to reinstall IP2Location plugin and re-upload BIN files (for database)

**Comment by ip2location** [comment]
Can I know which version of the plugin you have installed?

The error should be fixed in version 5.2.4.

**Comment by CinematicTree9** [comment]
Hey I’m using plugin in version 5.2.4
![IMG_1209](https://github.com/ip2location/ip2location-piwik/assets/52570208/a4771802-89d3-45e7-aae6-0f853caa2e1e)

**Comment by ip2location** [comment]
Can you please try to uninstall and install the plugin back again? Just to make sure there are no left over from the previous installation.

**Comment by CinematicTree9** [comment]
I removed the plug-in folder completely from the server and reinstalled. Unfortunately, the error occurs all the time.

**Comment by ip2location** [comment]
Please download the [latest version](https://github.com/ip2location/ip2location-piwik/releases/tag/5.2.5) which should fix the site ID issue.

**Comment by CinematicTree9** [comment]
Sometning is still wrong when I try to install plugin Matamo shows -> Update Matomo 5.0.3 to a newer version, Matomo >=4.0.0-b1,<5.0.0-b1 is required.

**Comment by ip2location** [comment]
Please get the version [5.2.6](https://github.com/ip2location/ip2location-piwik/releases/tag/5.2.6) for the fixes.
